# -*- coding: utf-8 -*-
"""TASK1 LINEAR ALGEBRA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ciXHvd1Sl1RIwZq_vV40Yj5iUmQjwghE
"""

# TASK1 ALGEBRA
import numpy as np

# Taking input for a 2x2 matrix
print("Enter elements of a 2x2 matrix:")

a11 = float(input("Enter a11: "))
a12 = float(input("Enter a12: "))
a21 = float(input("Enter a21: "))
a22 = float(input("Enter a22: "))

# Creating matrix
A = np.array([[a11, a12],
              [a21, a22]])

print("\nMatrix A:")
print(A)

eigenvalues = np.linalg.eigvals(A)

print("\nEigenvalues:")
print(eigenvalues)

# Input known eigenvalues
lambda1 = float(input("Enter first eigenvalue λ1: "))
lambda2 = float(input("Enter second eigenvalue λ2: "))

def find_eigenvector(matrix, eigenvalue):
    # Solve (A - λI)v = 0
    B = matrix - eigenvalue * np.eye(matrix.shape[0])

    # Solve using null space (SVD)
    u, s, vh = np.linalg.svd(B)
    # The last column of vh.T corresponds to the null space (smallest singular value)
    eigenvector = vh.T[:, -1]

    # Normalize for convenience
    eigenvector = eigenvector / eigenvector[0]  # make first component 1
    return eigenvector

v1 = find_eigenvector(A, lambda1)
v2 = find_eigenvector(A, lambda2)

print("\nEigenvector for λ1 = {}: {}".format(lambda1, v1))
print("Eigenvector for λ2 = {}: {}".format(lambda2, v2))

import numpy as np
import matplotlib.pyplot as plt

# Transition matrix
A = np.array([[1.2, 0.1],
              [0.05, 1.1]])

# Initial population
x0 = np.array([1000, 800])

# Number of years
years = 20

# Store populations
population = np.zeros((years, 2))
population[0] = x0

# Population evolution
for i in range(1, years):
    population[i] = A @ population[i-1]

# Plot
plt.figure()
plt.plot(population[:,0], label="Population X")
plt.plot(population[:,1], label="Population Y")
plt.xlabel("Years")
plt.ylabel("Population")
plt.title("Population Dynamics of Two Groups")
plt.legend()
plt.show()