# -*- coding: utf-8 -*-
"""TASK2 CALCULUS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bDFUn-C6XWS1_GTJIBtQRzhbK-7mVt4X
"""

#TASK2 CALCULUS
import numpy as np

# Time (0 to 20 years)
t = np.linspace(0, 20, 21)

# Population function
P = 1000 * np.exp(0.03 * t)

# Growth rate (derivative)
growth_rate = 30 * np.exp(0.03 * t)

# Maximum growth rate
max_growth = growth_rate[-1]

print("Population over 20 years:\n", P)
print("\nGrowth rate over time:\n", growth_rate)
print("\nMaximum growth rate at t = 20:", max_growth)

import numpy as np
import matplotlib.pyplot as plt

# Time
t = np.linspace(0, 20, 100)

# Population function
P = 1000 * np.exp(0.03 * t)

# Plot
plt.figure()
plt.plot(t, P)
plt.xlabel("Time (years)")
plt.ylabel("Population")
plt.title("Population Growth of Paris Over 20 Years")
plt.show()