# -*- coding: utf-8 -*-
"""TASK3 PROBABILITY.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12pZz92uoHJc7eqJi9KWIq4I2KoSXczja
"""

#TASK3 PROBABILITY
# Poisson parameter
import numpy as np
lambda_value = 5

expected_value = lambda_value
variance = lambda_value
standard_deviation = np.sqrt(variance)
print("Expected number of immigration events:", expected_value)
print("Variance of immigration events:", variance)
print("Standard deviation of immigration events:", standard_deviation)

import numpy as np
import matplotlib.pyplot as plt
from math import factorial

# Poisson parameter
lam = 5

# Events
k = np.arange(0, 15)

# Poisson PMF
poisson_pmf = [(np.exp(-lam) * lam**i) / factorial(i) for i in k]

# Plot
plt.figure()
plt.bar(k, poisson_pmf)
plt.xlabel("Number of Immigration Events per Year")
plt.ylabel("Probability")
plt.title("Poisson Distribution (λ = 5)")
plt.show()

