# -*- coding: utf-8 -*-
"""TASK4 STATISTICS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/116VbJLvDM2WSPMiJRM0FfFVaW0KzxUlp
"""

#TASK4 STATISTICS
import numpy as np
from scipy import stats

# District population data
data = np.array([1050, 1070, 1065, 1080, 1045, 1075, 1060, 1070])

n = len(data)

# Sample mean
mean = np.mean(data)

# Sample standard deviation
std_dev = np.std(data, ddof=1)

# 95% confidence interval
confidence_level = 0.95
t_critical = stats.t.ppf((1 + confidence_level) / 2, df=n-1)

margin_of_error = t_critical * (std_dev / np.sqrt(n))

confidence_interval = (mean - margin_of_error, mean + margin_of_error)

print("Sample mean:", mean)
print("Sample standard deviation:", std_dev)
print("95% Confidence Interval:", confidence_interval)

import numpy as np
import matplotlib.pyplot as plt
from scipy import stats

# Data
data = np.array([1050, 1070, 1065, 1080, 1045, 1075, 1060, 1070])

# Sample statistics
mean = np.mean(data)
std = np.std(data, ddof=1)
n = len(data)

# 95% confidence interval
t_critical = stats.t.ppf(0.975, df=n-1)
margin = t_critical * (std / np.sqrt(n))
lower = mean - margin
upper = mean + margin

# Plot histogram
plt.figure(figsize=(8,5))
plt.hist(data, bins='auto', color='skyblue', edgecolor='black', alpha=0.7)

# Plot sample mean
plt.axvline(mean, color='red', linestyle='--', linewidth=2, label=f"Sample Mean = {mean:.2f}")

# Plot confidence interval
plt.axvline(lower, color='green', linestyle=':', linewidth=2, label=f"Lower 95% CI = {lower:.2f}")
plt.axvline(upper, color='green', linestyle=':', linewidth=2, label=f"Upper 95% CI = {upper:.2f}")

# Scatter individual points for clarity
plt.scatter(data, np.zeros_like(data), color='black', marker='o', s=50, label='District Data')

# Labels and title
plt.xlabel("Population")
plt.ylabel("Frequency")
plt.title("District Population Distribution with 95% Confidence Interval")
plt.legend()
plt.grid(axis='y', alpha=0.3)
plt.show()

